// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgzwodpszetoaspnhhja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnendvZHBzemV0b2FzcG5oaGphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzQwNTgsImV4cCI6MjA2ODM1MDA1OH0.rHcEbyZM5fOu-KHlcA35f5eCVepwdWUYE-rqVCpg-Hc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});